#!/bin/bash
set +e

# populate /web/html if empty
if [ ! -d /web/html ]; then
  mkdir /web/html
  chown -R apache.www-data /web/html
fi

if [ ! -f /web/html/Include/Config.php ]; then
  cd /tmp
  # Latest Release Including RC
  #curl -sOL "$(jq -r ".[0] | .assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases" ))"
  # Latest Full Release
  curl -sOL "$(jq -r ".assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases/latest" ))"
  unzip -q *.zip
  cp -Rp ./churchcrm/. /web/html
  rm -R churchcrm

  # Since we've already set these passwords in the env file, lets just go ahead and put them in the database and skip the setup page.
  cp /web/html/Include/Config.php.example /web/html/Include/Config.php

  sed -i "s/||DB_SERVER_NAME||/$MYSQL_DB_HOST/g" /web/html/Include/Config.php
  sed -i "s/||DB_NAME||/$MYSQL_DATABASE/g" /web/html/Include/Config.php
  sed -i "s/||DB_USER||/$MYSQL_USER/g" /web/html/Include/Config.php
  sed -i "s/||DB_PASSWORD||/$MYSQL_PASSWORD/g" /web/html/Include/Config.php
  sed -i "s/||URL||//g" /web/html/Include/Config.php
  sed -i "s/||ROOT_PATH||//g" /web/html/Include/Config.php

  chown -R apache:www-data /web/html
fi
